### ISSUE TITLE
No longer working 

### ISSUE THREAD

**Issue by alistair-hmh** [silvenon/smph-todo-app#1]
I'm trying to get this working with the latest Create-React-App, Ava, JSDOM, and Node.

The instructions in your [blog post](https://semaphoreci.com/community/tutorials/getting-started-with-create-react-app-and-ava) do not seem to work anymore.

Do you have this working anywhere? If so, would it be possible to update this repo/the blog?

Out of interest, do you still use AVA to test with React these days?

FWIW: With your blog instructions I get the following error:

```shell
> cross-env NODE_ENV=test ava

./src/App.test.js:1
(function (exports, require, module, __filename, __dirname) { import test from 'ava';
                                                                     ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at extensions.(anonymous function) (./node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (./node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)

  1 exception

  ✖ src/App.test.js exited with a non-zero exit code: 1
npm ERR! Test failed.  See above for more details.
```

I had to update `jsdom`:

```javascript
const jsdom = require('jsdom');
const {JSDOM} = jsdom;

const dom = new JSDOM('<body></body>');

global.window = dom.window
global.document = global.window.document;
global.navigator = global.window.navigator;
```

**Comment by silvenon** [comment]
My blog post is old (at least in terms of how frontend technologies evolve) so it was bound to get outdated. I think it didn't contain create-react-app before, so I already updated it at least once.

I don't use AVA anymore, especially not with create-react-app, because at this point it's going against the grain when it comes to testing React. create-react-app already has Jest built-in, so I strongly recommend that you use it instead, you will have a much better time than hacking create-react-app to use a different test runner. Jest has excellent documentation and you will be able to get up and running in no time.
